# Generated by Django 2.1.7 on 2022-09-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumId', models.AutoField(primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=30, unique=True, verbose_name='专辑名字')),
                ('latestPlayTime', models.DateTimeField(verbose_name='最近播放时间')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistId', models.AutoField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=30, verbose_name='歌手名字')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionId', models.AutoField(primary_key=True, serialize=False)),
                ('album', models.ManyToManyField(to='index.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='消息发布的时间')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('comment', models.TextField(verbose_name='评论')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='消息发布的时间')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trackId', models.AutoField(primary_key=True, serialize=False)),
                ('trackName', models.CharField(max_length=30, unique=True, verbose_name='歌曲名字')),
                ('latestPlayTime', models.DateTimeField(verbose_name='最近播放时间')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Album', verbose_name='专辑')),
                ('artist', models.ManyToManyField(to='index.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('avatarImage', models.TextField(verbose_name='头像图片链接')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='被回复的人', to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='reply',
            name='mainComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发言者', to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Artist', verbose_name='专辑的作者'),
        ),
    ]
