# Generated by Django 3.2.15 on 2022-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220901_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatarImage',
            field=models.CharField(max_length=100, null=True, verbose_name='头像图片链接'),
        ),
    ]
