# Generated by Django 3.2.15 on 2022-09-03 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_userinfo_avatarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='intro',
            field=models.TextField(default='', verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='album',
            name='uploadState',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='上传状态'),
        ),
        migrations.AddField(
            model_name='album',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.userinfo', verbose_name='上传专辑的作者'),
        ),
        migrations.AlterField(
            model_name='album',
            name='latestPlayTime',
            field=models.DateTimeField(null=True, verbose_name='最近播放时间'),
        ),
        migrations.AlterField(
            model_name='track',
            name='latestPlayTime',
            field=models.DateTimeField(null=True, verbose_name='最近播放时间'),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackName',
            field=models.CharField(max_length=30, verbose_name='歌曲名字'),
        ),
    ]
