# Generated by Django 3.2.15 on 2022-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220903_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumImage',
            field=models.CharField(default='', max_length=100, verbose_name='专辑封面'),
        ),
    ]
