# Generated by Django 3.2.15 on 2022-09-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_album_albumimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumImage',
            field=models.CharField(default='', max_length=100, verbose_name='专辑封面'),
        ),
    ]
