# Generated by Django 3.2.15 on 2022-09-03 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_album_albumimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='latestPlayTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='最近播放时间'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.userinfo'),
        ),
    ]
