# Generated by Django 3.2.15 on 2022-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20220906_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
