# Generated by Django 3.2.15 on 2022-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='id',
        ),
        migrations.AddField(
            model_name='reply',
            name='replyComment',
            field=models.TextField(default='', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='reply',
            name='replyId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='消息发布的时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='消息发布的时间'),
        ),
    ]
