# Generated by Django 3.2.15 on 2022-09-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_reply_replyid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-like']},
        ),
    ]
