# Generated by Django 3.2.15 on 2022-09-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
