# Generated by Django 3.2.15 on 2022-09-06 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='latestPlayTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='最近播放时间'),
        ),
    ]
