# Generated by Django 3.2.15 on 2022-09-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_track_latestplaytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='length',
            field=models.CharField(max_length=6, null=True, verbose_name='歌曲长度'),
        ),
    ]
