# Generated by Django 3.2.15 on 2022-09-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_track_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='length',
            new_name='duration',
        ),
    ]
