# Generated by Django 3.2.15 on 2022-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('0', 'user'), ('1', 'manager')], default='0', max_length=10, verbose_name='身份'),
        ),
    ]
