# Generated by Django 3.2.15 on 2022-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploadState',
            field=models.CharField(choices=[('0', '审核未通过'), ('1', '待审核'), ('2', '审核已通过')], default='1', max_length=20, verbose_name='上传状态'),
        ),
    ]
