# Generated by Django 3.2.15 on 2022-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20220910_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='歌手'),
        ),
    ]
