# Generated by Django 3.2.15 on 2022-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='musicUrl',
            field=models.TextField(null=True, verbose_name='歌曲链接'),
        ),
    ]
