# Generated by Django 3.2.15 on 2022-09-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_alter_track_musicurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='musicUrl',
            field=models.CharField(max_length=200, null=True, verbose_name='歌曲链接'),
        ),
    ]
