# Generated by Django 3.2.15 on 2022-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_alter_track_musicurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='musicUrl',
        ),
        migrations.AddField(
            model_name='track',
            name='musicId',
            field=models.CharField(max_length=10, null=True, verbose_name='歌曲链接id'),
        ),
    ]
